Trait {
	#name : #TMASimulationExperimentalToGlobalEvents,
	#traits : 'MolComponentEvents',
	#classTraits : 'MolComponentEvents classTrait',
	#category : #MolAntsExperimental
}

{ #category : #'events - lifecycle' }
TMASimulationExperimentalToGlobalEvents >> simulationStepSent: aStep [

	
]

{ #category : #'events - lifecycle' }
TMASimulationExperimentalToGlobalEvents >> started [

	
]

{ #category : #'events - lifecycle' }
TMASimulationExperimentalToGlobalEvents >> stopped [

	
]
