Trait {
	#name : #TMASimulationExperimentalServices,
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : #MolAntsExperimental
}

{ #category : #services }
TMASimulationExperimentalServices >> ants [

	

]

{ #category : #services }
TMASimulationExperimentalServices >> insects [

	
]

{ #category : #services }
TMASimulationExperimentalServices >> isRunning [

]

{ #category : #services }
TMASimulationExperimentalServices >> start [

	
]

{ #category : #services }
TMASimulationExperimentalServices >> step [

	
]

{ #category : #services }
TMASimulationExperimentalServices >> stop [

	
]

{ #category : #services }
TMASimulationExperimentalServices >> storage [

	
]
