Trait {
	#name : #TMASimulationExperimentalServices,
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : #MolAntsExperimental
}

{ #category : #services }
TMASimulationExperimentalServices >> getAnts [

	
]

{ #category : #services }
TMASimulationExperimentalServices >> getInsects [

	
]

{ #category : #services }
TMASimulationExperimentalServices >> getReturningStep [

	
]

{ #category : #services }
TMASimulationExperimentalServices >> getStep [

	
]

{ #category : #services }
TMASimulationExperimentalServices >> isRestoring [

	
]

{ #category : #services }
TMASimulationExperimentalServices >> isRunning [

]

{ #category : #services }
TMASimulationExperimentalServices >> restoreOneStepBefore [
]

{ #category : #services }
TMASimulationExperimentalServices >> start [

	
]

{ #category : #services }
TMASimulationExperimentalServices >> startTimeTravel [

	
]

{ #category : #services }
TMASimulationExperimentalServices >> stop [

	
]

{ #category : #services }
TMASimulationExperimentalServices >> stopTimeTravel [

	
]
