Trait {
	#name : #TMATimeTravelExperimentalEvents,
	#traits : 'MolComponentEvents',
	#classTraits : 'MolComponentEvents classTrait',
	#category : #MolAntsExperimental
}

{ #category : #events }
TMATimeTravelExperimentalEvents >> restoreFrom: aMemento [

	
]

{ #category : #events }
TMATimeTravelExperimentalEvents >> startTimeTravel [

	
]

{ #category : #events }
TMATimeTravelExperimentalEvents >> stopTimeTravel [

	
]
