Trait {
	#name : #TMATimeTravelExperimentalServices,
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : #MolAntsExperimental
}

{ #category : #services }
TMATimeTravelExperimentalServices >> isPlayingBackward [ 

	
]

{ #category : #services }
TMATimeTravelExperimentalServices >> isReplaying [
]

{ #category : #services }
TMATimeTravelExperimentalServices >> isRestoring [
]

{ #category : #services }
TMATimeTravelExperimentalServices >> playBackward [

	
]

{ #category : #services }
TMATimeTravelExperimentalServices >> replay [

	
]

{ #category : #services }
TMATimeTravelExperimentalServices >> restoreAtStep: aStep [
]

{ #category : #services }
TMATimeTravelExperimentalServices >> restoringStep [ 

	
]

{ #category : #services }
TMATimeTravelExperimentalServices >> save: aComponent at: aStep [
]

{ #category : #services }
TMATimeTravelExperimentalServices >> startTimeTravel [ 
]

{ #category : #services }
TMATimeTravelExperimentalServices >> stopTimeTravel [

	
]
