"
This service is provided by the ant implementation isn't used by another component. However, it permits to describe methods that the ant implementation need to provide.
"
Trait {
	#name : #TMAAntServices,
	#instVars : [
		'stage'
	],
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : #MolAnts
}

{ #category : #services }
TMAAntServices >> getRole [

	
]

{ #category : #services }
TMAAntServices >> getRoleName [
]

{ #category : #services }
TMAAntServices >> getStage [
]

{ #category : #services }
TMAAntServices >> getStageName [

	
]
