"
Feeding points provide this event that is consumed by the simulation manager. This event describe one methods that aim to be implemented by feeding points.
"
Trait {
	#name : #TMAFeedingPointServices,
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : #MolAnts
}

{ #category : #events }
TMAFeedingPointServices >> eated [
]

{ #category : #accessing }
TMAFeedingPointServices >> position [
]
