"
This service is provided by the pheromone implementation and used by the ground and the simulation manager. It provides two methods to retrieve the pheromones dictionaries. This aim to draw pheromones on the canvas and to detect if an ant is around pheromones.
"
Trait {
	#name : #TMAPheromoneServices,
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : #MolAnts
}

{ #category : #services }
TMAPheromoneServices >> getMaxIntensity [
]

{ #category : #services }
TMAPheromoneServices >> getPheromonesDict [
]

{ #category : #services }
TMAPheromoneServices >> getPheromonesReturnDict [
]
