Trait {
	#name : #TMATimeTravelServices,
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : #MolAnts
}

{ #category : #services }
TMATimeTravelServices >> creationOf: aComponentMemento at: aStep [

]

{ #category : #services }
TMATimeTravelServices >> isOnTheFirstStep [

	
]

{ #category : #services }
TMATimeTravelServices >> isOnTheLastStep [

	
]

{ #category : #services }
TMATimeTravelServices >> isPlayingBackward [ 

	
]

{ #category : #services }
TMATimeTravelServices >> isReplaying [
]

{ #category : #services }
TMATimeTravelServices >> isRestoring [

	
]

{ #category : #services }
TMATimeTravelServices >> playBackward [

	
]

{ #category : #services }
TMATimeTravelServices >> removeOf: aComponentMemento at: aStep [
]

{ #category : #services }
TMATimeTravelServices >> replay [

	
]

{ #category : #services }
TMATimeTravelServices >> restoreAtStep: aStep [
]

{ #category : #services }
TMATimeTravelServices >> restoreOneStepAfter [ 

	
]

{ #category : #services }
TMATimeTravelServices >> restoreOneStepBefore [

	
]

{ #category : #services }
TMATimeTravelServices >> restoringStep [ 

	
]

{ #category : #services }
TMATimeTravelServices >> save: aComponent at: aStep [
]

{ #category : #services }
TMATimeTravelServices >> saveTheSimulationAt: aStep [

	
]

{ #category : #services }
TMATimeTravelServices >> startTimeTravel [
]

{ #category : #services }
TMATimeTravelServices >> stopTimeTravel [

	
]
