Trait {
	#name : #TMATimeTravelServices,
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : #MolAnts
}

{ #category : #services }
TMATimeTravelServices >> creationOf: aComponentMemento at: aStep [

]

{ #category : #services }
TMATimeTravelServices >> initializationAt: aStep [

	
]

{ #category : #services }
TMATimeTravelServices >> isRestoring [

	
]

{ #category : #services }
TMATimeTravelServices >> removeOf: aComponentMemento at: aStep [
]

{ #category : #services }
TMATimeTravelServices >> save: aComponent at: aStep [
]

{ #category : #services }
TMATimeTravelServices >> saveTheSimulationAt: aStep [

	
]
