Trait {
	#name : #TimeTravelServices,
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : #MolTimeTravel
}

{ #category : #services }
TimeTravelServices >> activationOf: aComponent [

	
]

{ #category : #services }
TimeTravelServices >> creationOf: aComponent [

	
]

{ #category : #services }
TimeTravelServices >> deletionOf: aComponent [

	
]

{ #category : #services }
TimeTravelServices >> isRestoring [

	
]

{ #category : #services }
TimeTravelServices >> passivationOf: aComponent [

	
]

{ #category : #services }
TimeTravelServices >> save: aComponentMemento [

	
]

{ #category : #services }
TimeTravelServices >> saveEvent: aMethodName performBy: aComponent withParameters: someParameters needToReplay: aBoolean [
]

{ #category : #services }
TimeTravelServices >> saveService: aMethodName performBy: aComponent withParameters: someParameters needToReplay: aBoolean [
]

{ #category : #services }
TimeTravelServices >> saveTheApplication [

	
]
