Trait {
	#name : #TMATimeTravelServices,
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : #MolAntsTimeTravel
}

{ #category : #services }
TMATimeTravelServices >> creationOf: aComponent [

	
]

{ #category : #services }
TMATimeTravelServices >> deletionOf: aComponent [

	
]

{ #category : #services }
TMATimeTravelServices >> isRestoring [

	
]

{ #category : #services }
TMATimeTravelServices >> save: aComponentMemento [

	
]

{ #category : #services }
TMATimeTravelServices >> saveTheApplication [

	
]
