Trait {
	#name : #TMATimeTravelEvents,
	#traits : 'MolComponentEvents',
	#classTraits : 'MolComponentEvents classTrait',
	#category : #MolAntsTimeTravel
}

{ #category : #events }
TMATimeTravelEvents >> restoreFrom: aMemento [

	
]

{ #category : #events }
TMATimeTravelEvents >> saveForTimeTravel [

	
]

{ #category : #events }
TMATimeTravelEvents >> startTimeTravel [

	
]

{ #category : #events }
TMATimeTravelEvents >> stopTimeTravel [

	
]
